server:
  port: 9086
management:
    health:
      binders:
        enabled: false
spring:
  kafka:
    properties:
      topic: stats
      spring:
        json:
          value:
            default:
              type: org.temkarus0070.analyticorderservice.models.OrderDTO
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    streams:
      bootstrap-servers: localhost:9092
      properties:
        default.key.serde:  org.apache.kafka.streams.kstream.WindowedSerdes$TimeWindowedSerde
        default.value.serde:   org.springframework.kafka.support.serializer.JsonSerde
        spring:
          json:
            value:
                default:
                  type: org.temkarus0070.analyticorderservice.models.OrderDTO
            trusted:
              packages: org.temkarus0070.analyticorderservice.models
        windowed.inner.class.serde: org.temkarus0070.analyticorderservice.kafkaStream.OrderStatusDataSerde
        window:
          size.ms: 60000

      replication-factor: 1
      application-id: analytic-app
  application:
    name:  app
