server:
  port: 9086
project:
  title: kafka analytic app
  description: kafka analytic app for orders
management:
    health:
      binders:
        enabled: false
spring:
  kafka:
    properties:
      topic: stats
      spring:
        json:
          value:
            default:
              type: org.temkarus0070.analyticorderservice.models.OrderDTO
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:127.0.0.1:9092}
      group-id: group-id
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    streams:
      bootstrap-servers: ${KAFKA_SERVER:127.0.0.1:9092}
      properties:
        default:
          key.serde: org.apache.kafka.streams.kstream.WindowedSerdes$TimeWindowedSerde
          value.serde: org.springframework.kafka.support.serializer.JsonSerde
          windowed.key.serde.inner: org.temkarus0070.analyticorderservice.kafkaStream.OrderStatusDataSerde
        spring:
          json:
            value:
              default:
                type: org.temkarus0070.analyticorderservice.models.OrderDTO
            trusted:
              packages: org.temkarus0070.analyticorderservice.models

        window:
          size.ms: 60000

      replication-factor: 1
      application-id: analytic-app


  application:
    name: analytic-app
opentracing.jaeger:
  udp-sender:
    host: ${JAEGER_HOST:localhost}
    port: 6831
  log-spans: true